### ISSUE TITLE
CNA_CGH=TRUE

### ISSUE THREAD

**Issue by aedin** [LiNk-NY/RTCGAToolbox#2]
hi
CNA_CGH=TRUE is falling over

**Comment by LiNk-NY** [comment]
For some diseases, CNA_CGH data may be unavailable and I'm not sure why this is.
The show/print method should say whether there is data in the CNA_CGH slot or not.

**Comment by LiNk-NY** [comment]
This may have been a bug with the filename. I would need more information. It's working for me.

**Comment by lwaldron** [comment]
Aedin, reproducible example please :)



—

**Comment by aedin** [comment]
Hi Levi
It may have been an issue with the different version of RTCGAtoolbox. 
The following worked for me


setMethod("nchar", "ANY", base::nchar)
ov <- getFirehoseData("OV", runDate=rd, gistic2_Date=ad, 
RNAseq_Gene=TRUE, CNA_CGH=TRUE, CNV_SNP = TRUE,CNA_SNP =TRUE, 
Methylation=TRUE, Mutation=TRUE, mRNA_Array=TRUE,  RPPA=TRUE)
ov

# Workaround, as the runDate and analyseData are missing from slots. 
these are needed later
ov@runDate<-rd
ov@gistic2Date<- ad

**Comment by LiNk-NY** [comment]
Hi Aedin, 
It seems like it was an issue with the version of RTCGAToolbox that you were using. I added those slots to the class on my fork some time ago.

**Comment by aedin** [comment]
Hi Macel
The slots existed but where empty. Glad its fixed
Aedin
